'use server';

import { requireAuth } from '@/lib/auth';
import { can } from '@/lib/rbac';
import { dbOne, db } from '@/lib/db';
import { revalidatePath } from 'next/cache';

const AI_PROXY = process.env.AI_PROXY_URL ?? 'http://mps-ai-proxy:3103';

// ── Allowed values (server-side validation) ──────────────────────
const VALID_URGENCY = ['Low', 'Medium', 'High', 'Critical'] as const;

export interface CreateCaseResult {
  ok: boolean;
  error?: string;
  caseId?: number;
}

/**
 * Creates a new case with resident details and runs the full
 * causality engine pipeline: analysis → letters → doc requirements.
 * Case number is auto-generated by the DB trigger.
 */
export async function createCaseWithAnalysis(
  _prev: CreateCaseResult | null,
  formData: FormData
): Promise<CreateCaseResult> {
  const session = await requireAuth();
  if (!can(session.role, 'cases:create')) {
    return { ok: false, error: 'You do not have permission to create cases.' };
  }

  // ── Extract and validate fields ────────────────────────────────
  const residentName = (formData.get('resident_name') as string)?.trim();
  if (!residentName || residentName.length < 2) {
    return { ok: false, error: 'Resident name is required (min 2 characters).' };
  }
  if (residentName.length > 100) {
    return { ok: false, error: 'Resident name must be 100 characters or fewer.' };
  }

  const nricMasked   = (formData.get('nric_masked') as string)?.trim() || null;
  const contactPhone = (formData.get('contact_phone') as string)?.trim() || null;
  const transcript   = (formData.get('transcript') as string)?.trim() || '';

  if (!transcript) {
    return { ok: false, error: 'Interview notes / transcript is required for AI analysis.' };
  }

  // ── Step 1: Look up writer context for letter assembly ─────────
  const userRow = await dbOne<{ name: string; constituency_name: string | null }>(
    `SELECT u.name, c.name AS constituency_name
     FROM users u
     LEFT JOIN constituencies c ON c.id = u.constituency_id
     WHERE u.id = $1`,
    [session.userId]
  );
  const mpName       = userRow?.name ?? 'The Member of Parliament';
  const constituency = userRow?.constituency_name ?? '';

  // ── Step 2: Run Causality Engine ───────────────────────────────
  const conversation = [{ role: 'user', content: transcript }];

  let causalGraph: Record<string, unknown>;
  let letters: Array<{ agency: string; agencyLabel?: string; content: string }> = [];

  try {
    const proxyResponse = await fetch(`${AI_PROXY}/api/ai/causality`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ conversation, mpName, constituency, writerName: mpName }),
      signal: AbortSignal.timeout(180_000),
    });

    if (!proxyResponse.ok) {
      const body = await proxyResponse.json().catch(() => ({})) as Record<string, unknown>;
      return { ok: false, error: `AI analysis failed: ${String(body.error ?? `Status ${proxyResponse.status}`)}` };
    }

    const payload = await proxyResponse.json() as {
      causalGraph: Record<string, unknown>;
      letters: Array<{ agency: string; agencyLabel?: string; content: string }>;
    };
    causalGraph = payload.causalGraph;
    letters = payload.letters ?? [];
  } catch (err) {
    const msg = (err as Error).message;
    console.error('[createCase] AI proxy unreachable:', msg);
    return { ok: false, error: `AI proxy unreachable: ${msg}` };
  }

  // ── Step 3: Extract AI-derived fields ──────────────────────────
  const aiUrgency = (causalGraph.urgency as { overall?: string })?.overall;
  const urgency = aiUrgency && (VALID_URGENCY as readonly string[]).includes(aiUrgency)
    ? aiUrgency
    : 'Medium';

  const keyFacts = (causalGraph.keyFacts as string[]) ?? [];
  const suggestedAgencies = (causalGraph.agencyRoutes as Array<{ agency: string }>)
    ?.map(r => r.agency)
    .filter(Boolean) ?? [];

  // Extract category from causal graph domains
  const agencyRoutes = (causalGraph.agencyRoutes as Array<{ agency: string; priority: string }>) ?? [];
  const rawCategory = deriveCategory(agencyRoutes);
  const category = rawCategory ? rawCategory.slice(0, 100) : null;  // VARCHAR(100) guard
  const summary = ((causalGraph.summary as string) ?? transcript.slice(0, 500)).slice(0, 2000);
  const coreRequest = ((causalGraph.coreRequest as string) ?? null)?.slice(0, 500) ?? null;

  // ── Step 4: Insert case ────────────────────────────────────────
  const rows = await db<{ id: number }>(
    `INSERT INTO cases
       (constituency_id, resident_name, nric_masked, contact_phone,
        category, urgency, status, summary, core_request,
        key_facts, suggested_agencies, causal_graph)
     VALUES ($1, $2, $3, $4, $5, $6, 'new', $7, $8, $9, $10, $11)
     RETURNING id`,
    [
      session.constituencyId,
      residentName,
      nricMasked,
      contactPhone,
      category,
      urgency,
      summary,
      coreRequest,
      keyFacts,
      suggestedAgencies,
      JSON.stringify(causalGraph),
    ]
  );

  const newCaseId = rows[0]?.id;
  if (!newCaseId) {
    return { ok: false, error: 'Failed to create case. Please try again.' };
  }

  // ── Step 5: Persist document requirements ──────────────────────
  const docReqs = (causalGraph.documentRequirements ?? []) as Array<{
    agency: string; documentType: string; reason: string;
    relatedNodeIds?: string[]; required?: boolean;
    sourceType?: string; sourceInstitution?: string;
  }>;

  for (const req of docReqs) {
    if (!req.documentType || !req.agency) continue;
    await dbOne(
      `INSERT INTO document_requirements
         (case_id, agency, document_type, reason, related_node_ids, required, source_type, source_institution)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
      [
        newCaseId, req.agency.slice(0, 100), req.documentType, req.reason ?? '',
        req.relatedNodeIds ?? [], req.required ?? true,
        req.sourceType === 'government_request' ? 'government_request' : 'resident',
        req.sourceInstitution ?? null,
      ]
    );
  }

  // ── Step 6: Persist letters ────────────────────────────────────
  let lettersCreated = 0;
  for (const letter of letters) {
    if (!letter.agency || !letter.content) continue;
    await dbOne(
      `INSERT INTO letters (case_id, agency, agency_label, content, status, generated_by)
       VALUES ($1,$2,$3,$4,'draft',$5)`,
      [newCaseId, letter.agency.slice(0, 100), letter.agencyLabel?.slice(0, 100) ?? null, letter.content, session.userId]
    );
    lettersCreated++;
  }

  // ── Step 7: Audit trail ────────────────────────────────────────
  await dbOne(
    `INSERT INTO case_events (case_id, actor_id, actor_role, action, detail)
     VALUES ($1,$2,$3,'case_created',$4)`,
    [
      newCaseId, session.userId, session.role,
      JSON.stringify({
        created_by: session.role,
        lettersCreated,
        documentRequirements: docReqs.length,
        urgency,
      }),
    ]
  );

  revalidatePath('/dashboard/cases');
  revalidatePath(`/dashboard/cases/${newCaseId}`);

  return { ok: true, caseId: newCaseId };
}

/**
 * Derive a case category from the primary agency route.
 * Maps agencies to their primary domain for classification.
 */
function deriveCategory(
  routes: Array<{ agency: string; priority: string }>
): string | null {
  const primary = routes.find(r => r.priority === 'primary');
  if (!primary) return null;

  const AGENCY_CATEGORY: Record<string, string> = {
    HDB: 'Housing', 'Town Council': 'Housing',
    CPF: 'Financial', ComCare: 'Financial', SSO: 'Financial', CDC: 'Financial',
    MSF: 'Family', FSC: 'Family',
    MOM: 'Employment', 'NTUC/e2i': 'Employment', WSG: 'Employment',
    MOH: 'Health', CHAS: 'Health', IMH: 'Health', 'SG Enable': 'Health',
    MOE: 'Social',
    ICA: 'Legal', LAB: 'Legal', SPF: 'Legal',
    'Yellow Ribbon': 'Social',
  };

  return AGENCY_CATEGORY[primary.agency] ?? null;
}

// ── HITL Gate 2 — Submit for Review ─────────────────────────────
// Transitions a case from new/drafting → pending_approval.
// BLOCKS unless the writer has confirmed every AI-extracted key fact.
// Writes an immutable audit event recording which facts were confirmed.
export async function submitForReview(
  caseId: number,
  confirmedFactIndices: number[]
): Promise<{ ok: boolean; error?: string }> {
  const session = await requireAuth();
  if (!can(session.role, 'cases:update')) {
    return { ok: false, error: 'Insufficient permissions.' };
  }

  // Fetch case and validate status
  const row = await dbOne<{ status: string; key_facts: string[] | null }>(
    'SELECT status, key_facts FROM cases WHERE id = $1',
    [caseId]
  );
  if (!row) return { ok: false, error: 'Case not found.' };
  if (row.status !== 'new' && row.status !== 'drafting') {
    return { ok: false, error: `Cannot submit — case is '${row.status}'. Only 'new' or 'drafting' cases can be submitted.` };
  }

  // Gate 2 enforcement: every key fact must be confirmed
  const keyFacts = row.key_facts ?? [];
  if (keyFacts.length > 0) {
    if (!confirmedFactIndices || confirmedFactIndices.length !== keyFacts.length) {
      return {
        ok: false,
        error: `Gate 2 blocked: ${keyFacts.length} fact(s) require confirmation. ${confirmedFactIndices?.length ?? 0} confirmed.`,
      };
    }
    // Verify indices are valid (0-based, contiguous)
    const expected = Array.from({ length: keyFacts.length }, (_, i) => i);
    const sorted = [...confirmedFactIndices].sort((a, b) => a - b);
    if (JSON.stringify(sorted) !== JSON.stringify(expected)) {
      return { ok: false, error: 'Gate 2 blocked: invalid fact confirmation indices.' };
    }
  }

  // Transition to pending_approval
  await dbOne(
    `UPDATE cases SET status = 'pending_approval', updated_at = NOW() WHERE id = $1`,
    [caseId]
  );

  // Audit trail — Gate 2 fact verification event
  await dbOne(
    `INSERT INTO case_events (case_id, actor_id, actor_role, action, detail)
     VALUES ($1, $2, $3, 'submitted_for_review', $4)`,
    [
      caseId,
      session.userId,
      session.role,
      JSON.stringify({
        gate: 'HITL-2-fact-verification',
        factsConfirmed: keyFacts.length,
        confirmedFacts: keyFacts,
        submittedBy: session.userId,
      }),
    ]
  );

  revalidatePath('/dashboard/cases');
  revalidatePath(`/dashboard/cases/${caseId}`);
  revalidatePath('/dashboard/approvals');
  revalidatePath('/dashboard');

  return { ok: true };
}

// ── HITL Gate 3 — Agency Override ────────────────────────────────
// Adds or removes an agency from the case's suggested_agencies.
// BLOCKS unless a documented reason (≥ 5 chars) is provided.
// Writes an immutable audit event recording the override and reason.
export async function overrideAgency(
  caseId: number,
  action: 'add' | 'remove',
  agency: string,
  reason: string
): Promise<{ ok: boolean; error?: string; agencies?: string[] }> {
  const session = await requireAuth();
  if (!can(session.role, 'cases:update')) {
    return { ok: false, error: 'Insufficient permissions.' };
  }

  // Gate 3 enforcement: reason is mandatory
  const trimmedReason = reason?.trim() ?? '';
  if (trimmedReason.length < 5) {
    return { ok: false, error: 'Gate 3 blocked: a documented reason (minimum 5 characters) is required for agency overrides.' };
  }

  const trimmedAgency = agency?.trim() ?? '';
  if (!trimmedAgency) {
    return { ok: false, error: 'Agency name is required.' };
  }

  // Fetch current agencies
  const row = await dbOne<{ suggested_agencies: string[] | null }>(
    'SELECT suggested_agencies FROM cases WHERE id = $1',
    [caseId]
  );
  if (!row) return { ok: false, error: 'Case not found.' };

  let agencies = row.suggested_agencies ?? [];

  if (action === 'add') {
    if (agencies.includes(trimmedAgency)) {
      return { ok: false, error: `Agency '${trimmedAgency}' is already in the list.` };
    }
    agencies = [...agencies, trimmedAgency];
  } else {
    if (!agencies.includes(trimmedAgency)) {
      return { ok: false, error: `Agency '${trimmedAgency}' is not in the list.` };
    }
    agencies = agencies.filter(a => a !== trimmedAgency);
  }

  // Persist updated agencies
  await dbOne(
    `UPDATE cases SET suggested_agencies = $1, updated_at = NOW() WHERE id = $2`,
    [agencies, caseId]
  );

  // Audit trail — Gate 3 agency override event
  await dbOne(
    `INSERT INTO case_events (case_id, actor_id, actor_role, action, detail)
     VALUES ($1, $2, $3, 'agency_override', $4)`,
    [
      caseId,
      session.userId,
      session.role,
      JSON.stringify({
        gate: 'HITL-3-agency-override',
        override_action: action,
        agency: trimmedAgency,
        reason: trimmedReason,
        resultingAgencies: agencies,
      }),
    ]
  );

  revalidatePath(`/dashboard/cases/${caseId}`);

  return { ok: true, agencies };
}
