import React, { useState } from 'react';
import { CheckCircle2, Copy, Check, LogOut } from 'lucide-react';

interface CaseSubmittedProps {
  referenceId: string;
  residentName: string;
  mpName: string;
  constituency: string;
  onDone: () => void;
}

const CaseSubmitted: React.FC<CaseSubmittedProps> = ({
  referenceId,
  residentName,
  mpName,
  constituency,
  onDone,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(referenceId);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      // Fallback for older browsers
      const el = document.createElement('textarea');
      el.value = referenceId;
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  return (
    <div className="flex flex-col h-full bg-white rounded-xl shadow-2xl overflow-hidden">
      {/* Header */}
      <div className="bg-green-600 text-white p-6 text-center">
        <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-3">
          <CheckCircle2 size={36} className="text-white" />
        </div>
        <h2 className="font-bold text-xl">Case Submitted</h2>
        <p className="text-green-100 text-sm mt-1">
          Thank you, {residentName}
        </p>
      </div>

      <div className="flex-1 p-6 space-y-6 overflow-y-auto">
        {/* Reference number — prominent, saveable */}
        <div className="bg-gray-50 border-2 border-gray-200 rounded-xl p-5 text-center">
          <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">
            Your Case Reference Number
          </p>
          <p className="text-3xl font-mono font-bold text-gray-900 tracking-widest mb-4">
            {referenceId}
          </p>
          <button
            onClick={handleCopy}
            className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-sm transition-all ${
              copied
                ? 'bg-green-100 text-green-700 border border-green-300'
                : 'bg-gray-800 text-white hover:bg-gray-700'
            }`}
          >
            {copied ? (
              <>
                <Check size={16} /> Copied!
              </>
            ) : (
              <>
                <Copy size={16} /> Copy Reference Number
              </>
            )}
          </button>
          <p className="text-xs text-red-600 font-medium mt-3">
            ⚠ Save this number — you will not be able to retrieve it later.
          </p>
        </div>

        {/* What happens next */}
        <div className="space-y-3">
          <p className="text-sm font-bold text-gray-700">What happens next</p>
          <div className="space-y-2">
            {[
              `Your case has been routed to ${mpName}'s office (${constituency}).`,
              'A case writer will review your submission and the AI-generated summary.',
              'Human approval is required before any action is taken on your behalf.',
              'If your case was marked urgent, a priority slot may be offered.',
            ].map((step, i) => (
              <div key={i} className="flex items-start gap-3">
                <div className="w-5 h-5 bg-slate-100 rounded-full flex items-center justify-center text-xs font-bold text-slate-600 shrink-0 mt-0.5">
                  {i + 1}
                </div>
                <p className="text-sm text-gray-600">{step}</p>
              </div>
            ))}
          </div>
        </div>

        {/* AI disclosure reminder */}
        <div className="bg-blue-50 border border-blue-100 rounded-lg p-3">
          <p className="text-xs text-blue-700">
            <strong>AI Disclosure:</strong> Your case summary was generated by an AI assistant.
            All AI-generated content is subject to human review before any official response.
          </p>
        </div>
      </div>

      {/* Done button */}
      <div className="p-4 border-t border-gray-200">
        <button
          onClick={onDone}
          className="w-full flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-800 text-white font-bold py-3 rounded-xl transition-colors"
        >
          <LogOut size={18} /> End Session
        </button>
      </div>
    </div>
  );
};

export default CaseSubmitted;
